services:
  # src:
  #   depends_on:
  #     - mysql_db
  #   build:
  #     context: ./src
  #     dockerfile: Dockerfile
  #   image: django-cicd
  #   environment:
  #     - PORT=8000
  #   env_file:
  #     - src/.env
  #   ports:
  #     - "8000:8000"
  #   command: sh -c "chmod +x /app/migrate.sh && sh /app/migrate.sh && sh /app/entrypoint.sh".
  #   volumes:
  #     - staticfiles:/app/staticfiles
  
  
  mysql_db:
    image: mysql
    restart: always
    command: --explicit_defaults_for_timestamp # --port=3306 
    env_file:
      - src/.env
    expose:
      - 3306
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql/
      - ./src/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis
    restart: always
    expose:
      - 6380
    ports:
      - "6380:6380"
    volumes:
      - redis_data:/data
    entrypoint: redis-server --appendonly yes --port 6380
    

volumes:
  # staticfiles:
  #   external: true
  mysql_data:
  redis_data: